name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/NOTICE'
      - '**/NOTICE.md'
      - '**/CODE_OF_CONDUCT.md'
      - '**/CONTRIBUTING.md'
      - '**/SECURITY.md'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      packages: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
     
      # Run Build Project
    - name: Build with Gradle
      run: ./gradlew build
      
      # Upload Artifact Build
    - name: Upload AAR - ${{ env.main_project_module }}
      uses: actions/upload-artifact@v4
      with:
        name: androidVehicleConnectSDK.aar
        path: androidVehicleConnectSDK/build/outputs/aar/
