name: Documentation

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Checkout external template repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          repository: HARMAN-Automotive/CSP-Documentation
          path: CSP-Documentation
          token: ${{ secrets.REPO_TOKEN }}

      - name: Check files in the working directory
        run: |
          pwd
          ls

      - name: Configure Git
        id: git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew :androidvehicleconnectSDK:cyclonedxBom
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Archive SBOM
        run: cp ${{ github.workspace }}/androidVehicleConnectSDK/build/reports/bom.xml ./bom.xml

      - name: Download templates
        run: |
          cp ./CSP-Documentation/scripts/notice-generator.py ./notice-generator.py
          cp ./CSP-Documentation/template/NOTICE.template.md ./NOTICE.template
          cp ./CSP-Documentation/template/CODE_OF_CONDUCT.template.md ./CODE_OF_CONDUCT.md
          cp ./CSP-Documentation/template/SECURITY.template.md ./SECURITY.md
          cp ./CSP-Documentation/template/CONTRIBUTING.template.md ./CONTRIBUTING.md
          sed -i "s|{{repository}}|${{ github.repository }}|g" ./NOTICE.template
          sed -i "s|{{repository}}|${{ github.repository }}|g" ./CONTRIBUTING.md

      - name: Allow notice script to be executed
        run: chmod +x ./notice-generator.py

      - name: Execute script
        run: python ./notice-generator.py

      - name: Commit NOTICE
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git add NOTICE.md CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md
          git diff-index --quiet HEAD || git commit -am "Generate Documentation"
          git push

      
