name: Publish AAR to Maven Central

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  # install GPG
      - name: Install GPG
        run: choco install gnupg
        
  # Import GPG key
      - name: Set up GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_PASSPHRASE }}" > ~/.gnupg/passphrase
          
      # Build the AAR using Android SDK CLI
      - name: Clean build
        run: |
          ./gradlew clean
          
      - name: Generate AAR
        run: |
          ./gradlew build 

      - name: Generate Kdoc
        run: |
          ./gradlew :androidVehicleConnectSDK:dokkaHtml

    # setup GPG and Sign artifact
      - name: Setup gpg
        if: env.ARTIFACT_SIGNING_KEY
        id: gpg
        env:
          ARTIFACT_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "Importing key ..."
          echo "${ARTIFACT_SIGNING_KEY}" | gpg --batch --import --import-options import-show
          echo "Getting key id ..."
          key_id="$(echo "${ARTIFACT_SIGNING_KEY}" | gpg --batch --show-keys --with-colons | awk -F: '$1 == "sec" { print $5 }')"
          echo "::set-output name=key_id::${key_id}"
      - name: Sign artifacts
        if: env.GPG_KEYNAME
        env:
          GPG_KEYNAME: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          ./gradlew :androidVehicleConnectSDK:signReleasePublication \
              "-Psigning.keyName=${{ secrets.GPG_KEY_ID }}" \
              "-Psigning.password=${{ secrets.GPG_PASSPHRASE }}" \
              "-Psigning.secretKeyRingFile=${{ secrets.GPG_PRIVATE_KEY }}" \

    # Deploy to Sonatype OSSRH (Maven Central)
      - name: Publish to Maven Central
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew :androidVehicleConnectSDK:publishReleasePublicationToOssrhRepository
