name: Publish AAR to Maven Central

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
  # Import GPG key
      - name: Set up GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_PASSPHRASE }}" > ~/.gnupg/passphrase
          
      # Build the AAR using Android SDK CLI
      - name: Clean build
        run: |
          ./gradlew clean
          
      - name: Generate AAR
        run: |
          ./gradlew build 

      - name: Generate Kdoc
        run: |
          ./gradlew :androidVehicleConnectSDK:dokkaHtml

#    # Sign the AAR file
#      - name: Sign AAR file
#        run: |
#          AAR_FILE="androidVehicleConnectSDK/build/outputs/aar/androidVehicleConnectSDK-release.aar"
#          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output "${AAR_FILE}.asc" --detach-sig "$AAR_FILE"

    # Deploy to Sonatype OSSRH (Maven Central)
      - name: Publish to Maven Central
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew :androidVehicleConnectSDK:publishReleasePublicationToOssrhRepository
